### ISSUE TITLE
Do we need framebuffers to be square?

### ISSUE THREAD

**Issue by rbuch703** [kekscom/glx#2]
The current Framebuffer.setSize() method forces framebuffers to have a width identical to its height, making the framebuffer a square. Do we really need to enforce this restriction? It is quite wasteful in cases where the underlying target has width and height that differ significantly, i.e. when rendering into an off-screen buffer with the same aspect ratio as a physical wide-screen screen (for selection, SSAO, etc.).

Of course, framebuffer width and height should be ensured to be powers of two - as is already the case. GPUs are optimized for these buffer sizes and some WebGL implementations have limited support for non-power-of-two buffers. But AFAIK width and height can be different powers of two without any negative consequences.

**Comment by kekscom** [comment]
I'm fine with that. Who does the change? ;-)

**Comment by rbuch703** [comment]
I'll do it.
